sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 102786
  alioss:
    bucket-name: e99ac772f1600dbc5c896f594d73c416f9dbac311c9fcc40d3507b20
    access-key-secret: 8s2QgNh3bxrwlkzqoBMUiVrlkaWxLe
    access-key-id: LTAI5tKxFr3gySxYG72eKpNU
    endpoint: oss-cn-shanghai.aliyuncs.com
spring:
  redis:
    database: 0
    port: 6379
    host: localhost
