sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    bucket-name:
    access-key-secret:
    access-key-id:
    endpoint:
  wechat:
    appid:
    secret:
spring:
  redis:
    database: 0
    port: 6379
    host: localhost
